// Generated by CoffeeScript 1.3.3

module.exports = function(app) {
  app.get('/', function(req, res) {
    return res.render('index', {
      action: 'Do Something!'
    });
  });
  app.get('/action/:action', function(req, res) {
    return res.render('index', {
      action: req.params.action
    });
  });
  app.get('/hello', function(req, res) {
    return res.send('Hello Node');
  });
  return app.get('/hello/:name', function(req, res) {
    return res.send("Hello " + req.params.name);
  });
};
