// Generated by CoffeeScript 1.3.3

module.exports = function(app) {
  return app.post('/square', function(req, res) {
    var to_square;
    console.log(req.body);
    to_square = req.body.to_square;
    return res.send({
      result: to_square * to_square
    });
  });
};
